[tool.poetry]
name = "finalproject-sapronov-m25-555"
version = "0.1.0"
description = ""
authors = ["dmitriy.sapronov <dmitriy.sapronov@sbermarket.ru>"]
readme = "README.md"

packages = [
     { include = "valutatrade_hub" },
]

[tool.poetry.dependencies]
python = "^3.10"
prettytable = "^3.16.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
project = "valutatrade_hub.main:main"

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["venv", ".venv", "dist", "__pycache__", "constants.py"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = [] 